"""Authoritative contracts and state transitions for research runs."""

from .artifacts import (
    ArtifactPayload,
    ArtifactStore,
    FileArtifactStore,
    persist_research_artifacts,
)
from .compatibility import GitHubEvidenceV1Adapter
from .contracts import (
    Artifact,
    ArtifactManifest,
    CoverageResult,
    EventKind,
    EvidenceItem,
    GitHubEvidenceBundle,
    PreparedTerminal,
    ReportSpec,
    RepositorySnapshot,
    ResearchClaim,
    ResearchCommand,
    ResearchEvent,
    ResearchRunResult,
    RunError,
    RunSnapshot,
    RunStatus,
    canonicalize_github_report,
    deterministic_citation_block,
)
from .history import HistoryCursorError, HistoryPage, ResearchHistoryStore
from .intelligence import (
    INTELLIGENCE_SCHEMA_VERSION,
    ArtifactDescriptorV2,
    ArtifactManifestV2,
    ClaimRecord,
    CoverageDecision,
    EvidenceLocator,
    EvidenceRecord,
    GenericReportSpec,
    ResearchIntelligenceBundle,
    SourceReference,
    stable_claim_id,
    stable_evidence_id,
    stable_source_id,
)
from .memory import (
    MemoryNotFoundError,
    MemoryStateError,
    MemoryStoreUnavailableError,
    MemoryValidationError,
    UserMemory,
    UserMemoryStore,
)
from .pipeline import PreparedResearch, ResearchKernel
from .profiles import (
    CitationPolicy,
    CoveragePolicy,
    RenderedResearchTask,
    ReportSectionSpec,
    ResearchDimension,
    ResearchMode,
    ResearchProfile,
    ResearchProfileRegistry,
    ResearchTaskTemplate,
    RetrievalBudget,
    built_in_profile_registry,
)
from .quality import EvidenceGateBlockedError, EvidenceQualityGate
from .session import (
    NEVER_CANCELLED,
    CancellationRequestedError,
    CancellationToken,
    CheckpointPersistenceError,
    InvalidTransitionError,
    RunSession,
)

__all__ = [
    "NEVER_CANCELLED",
    "Artifact",
    "ArtifactPayload",
    "ArtifactManifest",
    "ArtifactStore",
    "CancellationRequestedError",
    "CheckpointPersistenceError",
    "CancellationToken",
    "CoverageResult",
    "canonicalize_github_report",
    "deterministic_citation_block",
    "EventKind",
    "EvidenceItem",
    "GitHubEvidenceBundle",
    "GitHubEvidenceV1Adapter",
    "EvidenceGateBlockedError",
    "EvidenceQualityGate",
    "FileArtifactStore",
    "HistoryCursorError",
    "HistoryPage",
    "InvalidTransitionError",
    "INTELLIGENCE_SCHEMA_VERSION",
    "PreparedTerminal",
    "ReportSpec",
    "ArtifactDescriptorV2",
    "ArtifactManifestV2",
    "ClaimRecord",
    "CoverageDecision",
    "EvidenceLocator",
    "EvidenceRecord",
    "GenericReportSpec",
    "ResearchIntelligenceBundle",
    "PreparedResearch",
    "ResearchKernel",
    "SourceReference",
    "stable_claim_id",
    "stable_evidence_id",
    "stable_source_id",
    "persist_research_artifacts",
    "ResearchCommand",
    "ResearchEvent",
    "ResearchRunResult",
    "RepositorySnapshot",
    "ResearchClaim",
    "RunError",
    "RunSession",
    "RunSnapshot",
    "RunStatus",
    "ResearchHistoryStore",
    "MemoryNotFoundError",
    "MemoryStateError",
    "MemoryStoreUnavailableError",
    "MemoryValidationError",
    "UserMemory",
    "UserMemoryStore",
    "CitationPolicy",
    "CoveragePolicy",
    "RenderedResearchTask",
    "ReportSectionSpec",
    "ResearchDimension",
    "ResearchMode",
    "ResearchProfile",
    "ResearchProfileRegistry",
    "ResearchTaskTemplate",
    "RetrievalBudget",
    "built_in_profile_registry",
]
